name: gasox_app
description: GASOX - Detector de Humo con ESP32

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  wifi_scan: ^0.4.1
  network_info_plus: ^4.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  workmanager: ^0.5.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
